# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CouchdbImporter
                                 A QGIS plugin
 This plugin allows importing vector data from the couchdb database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-01-30
        git sha              : $Format:%H$
        copyright            : (C) 2020 by MaximeGavens/Geomatys
        email                : contact@geomatys.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import json
import couchdb


# Custom exception
class CouchdbConnectorException(Exception):
    pass


# Main class
class CouchdbConnector(object):

    # Constructor
    def __init__(self, http, url, user, password):
        self.url = url
        self.user = user
        self.password = password
        self.address = http + "://" + self.user + ":" + self.password + "@" + self.url + "/"

        try:
            self.connection = couchdb.Server(self.address)
        except Exception:
            raise CouchdbConnectorException("Impossible de se connecter a la base")

    def getUrl(self):
        return self.url

    def getPort(self):
        return self.port

    def getUser(self):
        return self.User

    def getPassword(self):
        return self.password

    def getAddress(self):
        return self.address

    def getConnection(self):
        return self.connection
