# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CouchdbImporter
                                 A QGIS plugin
 This plugin allows importing vector data from the couchdb database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-01-30
        git sha              : $Format:%H$
        copyright            : (C) 2020 by MaximeGavens/Geomatys
        email                : contact@geomatys.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon, QStandardItem, QStandardItemModel
from qgis.PyQt.QtWidgets import QAction

from qgis.gui import QgsMessageBar
from qgis.core import QgsFeature, QgsGeometry, QgsVectorLayer, QgsProject, QgsSimpleMarkerSymbolLayerBase, QgsMarkerSymbol, QgsLineSymbol

from .couchdb_importer_dialog import CouchdbImporterDialog
import os.path

from .couchdb_connector import CouchdbConnector, CouchdbConnectorException
from .utils import Utils


class CouchdbImporter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CouchdbImporter_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Couchdb Importer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # Table content load from couchdb
        self.content = []
        self.contentSelected = []

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CouchdbImporter', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/couchdb_importer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Import Couchdb Data'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Couchdb Importer'),
                action)
            self.iface.removeToolBarIcon(action)

    def initialization(self):
        self.dlg.url.setEnabled(True)
        self.dlg.login.setEnabled(True)
        self.dlg.password.setEnabled(True)
        self.dlg.loginButton.setEnabled(True)
        self.dlg.comboBoxClass.clear()
        self.dlg.comboBoxClass.addItems(['TronconLit', 'TronconDigue', 'Desordre'])
        self.dlg.comboBoxClass.setEnabled(False)
        self.dlg.comboBoxDatabase.setEnabled(False)
        self.dlg.loadButton.setEnabled(False)

    def on_login_click(self):
        if self.dlg.login.text() == '' and self.dlg.password.text() == '':
            self.dlg.login.setText('admin')
            self.dlg.password.setText('admin')
        url = self.dlg.url.text()
        split_url = url.split("://")
        if len(split_url) == 2:
            http = split_url[0]
            addr = split_url[1]
        else:
            http = "localhost"
            addr = "5984"
        self.connector = CouchdbConnector(http, addr, self.dlg.login.text(), self.dlg.password.text())
        connection = self.connector.getConnection()
        self.dlg.comboBoxDatabase.clear()
        filtered_connection = []
        for name in connection:
            if not Utils.is_str_start_by_underscore(name):
                filtered_connection.append(name)
        self.dlg.comboBoxDatabase.addItems([name for name in filtered_connection])
        self.dlg.url.setEnabled(False)
        self.dlg.login.setEnabled(False)
        self.dlg.password.setEnabled(False)
        self.dlg.loginButton.setEnabled(False)
        self.dlg.comboBoxClass.setEnabled(True)
        self.dlg.comboBoxDatabase.setEnabled(True)
        self.dlg.loadButton.setEnabled(True)

    def on_load_click(self):
        try:
            couchdbServer = self.connector.getConnection()
            db = couchdbServer[self.dlg.comboBoxDatabase.currentText()]
            type = self.dlg.comboBoxClass.currentText()
            self.criteria = Utils.find_criteria_from_class(type)
            query = Utils.build_query(type)
            result = db.find(query)
            model = QStandardItemModel()
            for row in result:
                tupleContent = Utils.build_tuple(row, self.criteria)
                self.content.append(tupleContent)
                item = QStandardItem(tupleContent[0])
                item.setCheckState(Qt.Unchecked)
                item.setCheckable(True)
                model.appendRow(item)
            model.itemChanged.connect(self.on_item_changed)
            self.dlg.listView.setModel(model)
            self.dlg.comboBoxClass.setEnabled(False)
            self.dlg.comboBoxDatabase.setEnabled(False)
            self.dlg.loadButton.setEnabled(False)
        except CouchdbConnectorException as e:
            self.dlg.statusMessage.setText("load data failure")
            self.iface.messageBar().pushMessage("Couchdb Connector", str(e), level=QgsMessageBar.CRITICAL, duration=5)

    def on_object_click(self, item):
        model = self.dlg.listView.model()
        model.blockSignals(True)
        id = model.itemFromIndex(item)
        content_selected = []
        for cont in self.content:
            if cont[0] == str(id.text()):
                content_selected = cont
                break
        i = 0
        model = QStandardItemModel()
        for attribute in content_selected:
            it = QStandardItem(self.criteria[i] + " : " + str(attribute))
            model.appendRow(it)
            i = i + 1
        self.dlg.details.setModel(model)
        model.blockSignals(False)

    def on_select_all_click(self):
        model = QStandardItemModel()
        self.contentSelected.clear()
        for cont in self.content:
            item = QStandardItem(cont[0])
            item.setCheckState(Qt.Checked)
            item.setCheckable(True)
            model.appendRow(item)
            self.contentSelected.append(cont)
        self.dlg.listView.setModel(model)

    def on_reset_click(self):
        self.contentSelected = []
        self.content = []
        self.connector = None
        self.dlg.comboBoxDatabase.clear()
        self.dlg.comboBoxClass.clear()
        model = self.dlg.listView.model()
        if model:
            model.removeRows(0, model.rowCount())
        model2 = self.dlg.details.model()
        if model2:
            model2.removeRows(0, model2.rowCount())
        self.dlg.checkBox.setCheckState(Qt.Unchecked)
        self.initialization()

    def on_item_changed(self, item):
        if item.checkState() == Qt.Checked:
            self.add_from_content_selected(item)
        if item.checkState() == Qt.Unchecked:
            self.remove_from_content_selected(item)

    def add_from_content_selected(self, item):
        for content in self.content:
            if item.text() == content[0]:
                self.contentSelected.append(content)
                break

    def remove_from_content_selected(self, item):
        for content in self.content:
            if item.text() == content[0]:
                self.contentSelected.remove(content)
                break

    def add_layers(self):
        try:
            for content in self.contentSelected:
                id = content[0]
                index_geom = Utils.get_geometry_index(self.criteria)
                geom = content[index_geom]
                if geom is None:
                    continue
                geomType = geom.split(' ')[0]
                feature = QgsFeature()
                feature.setGeometry(QgsGeometry.fromWkt(geom))
                layer = QgsVectorLayer(geomType + "?crs=EPSG:4326", id, "memory")

                # style
                props = {}
                props["color"] = "123,0,0,255"
                props["width"] = "2.0"
                props["capstyle"] = "round"
                style = QgsLineSymbol.createSimple(props)

                layer.renderer().setSymbol(style)
                provider = layer.dataProvider()
                provider.addFeature(feature)
                layer.updateExtents()

                QgsProject.instance().addMapLayer(layer)
        except CouchdbConnectorException as e:
            self.dlg.statusMessage.setText("load layer failure")
            self.iface.messageBar().pushMessage("Couchdb Connector", str(e), level=QgsMessageBar.CRITICAL, duration=5)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = CouchdbImporterDialog()
            self.dlg.loginButton.clicked.connect(self.on_login_click)
            self.dlg.loadButton.clicked.connect(self.on_load_click)
            self.dlg.checkBox.stateChanged.connect(self.on_select_all_click)
            self.dlg.resetButton.clicked.connect(self.on_reset_click)
            self.dlg.listView.clicked.connect(self.on_object_click)
            self.dlg.url.setText("http://localhost:5984")

        self.initialization()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            self.add_layers()
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            # pass
